### ISSUE TITLE
It does not run dunkosmiloolump-1

### ISSUE THREAD

**Issue by ruuda** [aochagavia/FastAnts#1]
Running with [`dunkosmiloolump-1`](http://urchin.earth.li/icfpcontest/2004/Introduction) as the black ant produces the following error message:

```
thread 'main' panicked at 'Unknown instruction: TURN LEFT 1                             ;STATE 0  SA_START:0 SA_START', /home/ruud/repos/FastAnts/ant_lib/src/instruction.rs:103
```

Version: a0a94f0.

**Comment by aochagavia** [comment]
This happens because we don't handle comments. I will push a fix for it in the next minutes.
